{% set name = "coq-jupyter" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coq_jupyter-{{ version }}.tar.gz
  sha256: e337acb74e1b561729d13396b3c2fca5b63258b2759ed1796160d71315d038de

build:
  number: 0
  skip: true  # [win]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - coq >=8.6
    - python
    - jupyter_client
    - ipython
    - ipykernel
    - future
    - pexpect >=4.0

test:
  imports:
    - coq_jupyter

about:
  home: https://github.com/EugeneLoy/coq_jupyter
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Jupyter kernel for Coq'
  dev_url: https://github.com/EugeneLoy/coq_jupyter

extra:
  recipe-maintainers:
    - EugeneLoy
    - isuruf
    - slel
