{% set name = "coq-jupyter" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coq_jupyter-{{ version }}.tar.gz
  sha256: 63d991e9fe0278a721d61247b8970dcf5d29ef963026c0f80784d837d8647c5e

build:
  number: 0
  skip: true  # [win]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - jupyter_client
    - ipython
    - ipykernel
    - future
    - pexpect >=4.0
  run:
    - coq
    - python
    - jupyter_client
    - ipython
    - ipykernel
    - future
    - pexpect >=4.0

test:
  imports:
    - coq_jupyter

about:
  home: https://github.com/EugeneLoy/coq_jupyter
  license: Apache-2.0
  license_family: Apache
  # TODO: remove the file in recipe when MANIFEST.in gets updated, see
  # https://github.com/EugeneLoy/coq_jupyter/pull/35
  license_file: LICENSE
  summary: 'Jupyter kernel for Coq'
  dev_url: https://github.com/EugeneLoy/coq_jupyter

extra:
  recipe-maintainers:
    - isuruf
    - slel
