travis:
  secure:
    BINSTAR_TOKEN: bJkhimpd7aOVuJ8y3/ezMmBceyr0cIfc1MgtAJfX4UjhwdGJ+hBpmbWDrVaNH9RBVPbOednNUwp5hbmh7WhSxcrAzRUAvUFiC4D0PgKOraBFhpNWIgCOMNK0Uz87X/lhMuL4nWiqNXJLfuYz/HS8dQzHYhrQc9FWmXfdXWdW2iwplNCQTSIcVM7Di0IaitYNonthcApfVxTZmPmU/tZa4mCcAGm19gyF4hhS/8ke6gYlVlfC8gSTODnYe3i4lmzGF6g3xRDGgozcnObb2sjw1yTuZ3IB7pRe8UE4xlXFJD8H67neaI2FN8XpntjdODskp6NSl7TrMDofYKx5W8MW953AUL3zynLRp8wFDsQw+K1l2dhrq6VavM6qdCASN84Cr6kzgyqT0kwUkhBxueGrWTU28I2gU2kCFWisfrCe519Um5+sFAmwKAo970TTyWAtB3hAOhtjy0dugL1C4E6u5UDp+dDIaG/8gnphW61f7IyjN/8FjBblkWdot1SENofW9iQj7uSJaDlOMCbGqMEVDjqOc0wynxOk8iOHKZFC7jRwNWJys3H0TZ9kOymAl/LLl8On7adl3XnPFgRSqyXObu8fg/O+8qz4oj30JFhMjX2nXMjz3rH76HdghAkbW9RDeB5PuVGl6KtmimZ4/nLnHwlsotFdM3Bj3VPxcAUeiFI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
